config/routes.rb
Rails.application.routes.draw do

  get 'charges/create'
  get 'charges/new'

devise_for :users
resources :users
resources :wikis


resources :collaborators, only: [:index, :new, :destroy, :update]
resources :charges, only: [:new, :create]
resources :collaborators

get '/users/sign_out' => 'devise/sessions#destroy'
get "login", :to => "devise/sessions#new"
 get "register", :to => "devise/registrations#new"
 get "settings", :to => "devise/registrations#edit"
 get "logout",   :to => "devise/sessions#destroy"

get 'wikis/show'

get 'about' => 'welcome#about'
root "welcome#index"
 get 'users/downgrade/:customer' => 'charges#downgrade_account', as: :downgrade_account
get 'collaborators/:id' => 'collaborators#new', as: "new_collaborators_for_wiki"
end

app/models/amount.rb
class Amount
  def self.default
    15_00
  end
end

app/models/collaborator.rb
class Collaborator < ActiveRecord::Base
belongs_to :wiki
attr_accessor :email, :password, :role

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
has_many :collaborators



         enum role: [:standard, :premium, :admin, :collaborators]

end

app/models/wiki.rb
class Wiki < ActiveRecord::Base
  belongs_to :user
    has_many :collaborators
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  include Pundit
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
 def new
   @stripe_btn_data = {
     key: "#{ Rails.configuration.stripe[:publishable_key] }",
     description: "BigMoney Membership - #{current_user.name}",
     amount: Amount.default
   }
 end
 def create
   customer = Stripe::Customer.create(
     email: current_user.email,
     card: params[:stripeToken]
   )
   charge = Stripe::Charge.create(
     customer: customer.id,
     amount: Amount.default,
     description: "BigMoney Membership - #{current_user.email}",
     currency: 'usd'
   )
   flash[:notice] = "Thanks for all the money, #{current_user.email}! Feel free to pay me again."
   current_user.role = :premium
   current_user.save!

   rescue Stripe::CardError => e
     flash[:alert] = e.message
     redirect_to new_charge_path
 end
 def downgrade_account

   current_user.role = :standard
   current_user.save!
    redirect_to root_path
  end
end

app/controllers/collaborators_controller.rb
class CollaboratorsController < ApplicationController

def index
end

  def new
    @collaborator = Collaborator.new
    @user = User.all
    @wiki = Wiki.new
    @wiki = Wiki.find_by_id(params[:id])


#@wiki.collaboration_user_ids = []
#@wiki.save
 end

  def show
    @collaborator = Collaborator.find_by_id(params[:id])


  end

  def edit
    @wiki = Wiki.find(params[:id])
    authorize Collaborator
  end
    def update
      authorize Collaborator
      @wiki = Wiki.find(params[:id])
      collaborator = Collaborator.where(wiki_id: @wiki.id)
      collaboratiors.each do |collaborator|
      collaborator.destroy!
    end
      if @wiki.destroy
        flash[:notice] = "Collaborator was deleted successfully"
        redirect_to @wiki
      else
        flash.now[:alerts]= "Error. Try again."
        render :edit
      end
    end


        def create
          @wiki = Wiki.find_by_id(params[:wiki_id])
          @collaborator = Collaborator.new(user_id: params[:user_id], wiki_id: params[:wiki_id])
       if @collaborator.save
          flash[:notice] = "Congrats you have added a new collab"
        else
          flash[:error] = "Problem. Please try again"
          render :new
        end


    def destroy
  @collaborator.destroy!
   end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
      @users = User.all
  end

  def show
    @user = User.find_by_id(params[:id])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController

before_action :authenticate_user!
    def index
      @wikis = policy_scope(Wiki)
    end

  def show
    @wiki = Wiki.find(params[:id])
    authorize @wiki
  end

  def new
    @wiki = Wiki.new
  end

  def create
    @wiki = Wiki.new(wiki_params)
    @wiki.user = current_user
    if @wiki.save
      flash[:notice] = "Wiki saved."
      redirect_to @wiki
    else
      flash.now[:alert] = "Error"
      render :new
    end
  end

  def edit
    @wiki = Wiki.find(params[:id])
  end

  def update
    @wiki = Wiki.find(params[:id])
    @wiki.assign_attributes(wiki_params)
    if @wiki.save
      flash[:notice] = "Wiki was updated successfully"
      redirect_to @wiki
    else
      flash.now[:alerts]= "Errpr. Try again."
      render :edit
    end
  end

  def destroy
    authorize @wiki
    @wiki = find_id
    if @wiki.destroy
      flash[:notice] ="Deleted"
      redirect_to wikis_path
    else
      flash.now[:alert] = "Error"
      render :show
    end
  end
  
  private

  def wiki_params
    params.require(:wiki).permit(:title, :body, :private)
  end
  def find_id
    Wiki.find(params[:id])
  end
   def authorize_user
     wiki = Wiki.find(params[:id])
     unless current_user == wiki.user || current_user.admin?
       flash[:alert] = "You must be an admin, premium user or collaborator to do that."
       redirect_to wikis_path
     end
   end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wikis_helper.rb
module WikisHelper
  def user_is_authorized_for_wikis?(wiki)
      current_user.admin? || current_user.premium?
  end
end

app/views/charges/create.html.erb
<h2>Thanks! your now a premium member</h2>

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
   <h4>Click the button!</h4>
   <script class='stripe-button' src="https://checkout.stripe.com/checkout.js"
   data-key="<%= Rails.configuration.stripe[:publishable_key] %>" 
   data-amount="<%= @stripe_btn_data[:amount] %>"
   data-description="<%= @stripe_btn_data[:description] %>" ></script>
 <% end %>

app/views/collaborators/new.html.erb
<p>Add a Collaborator</p>
<div class="col-md-8">
	<%= form_for @collaborator do |f| %>
	<div class="field">
		<%= f.label :email %><br />
			<%= f.email_field :email%>
		</div>
		<div class="form-group">
	 	<%= f.submit "Add", class: 'btn btn-success' %>
		</div>
	<% end %>

app/views/collaborators/show.html.erb
<h1>show</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NewRailsProject</title>
  <p class="navbar-text pull-right">
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Log out", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>
</p>
<ul class="nav">
  <li class="active"><a href="/ideas">Ideas</a></li>
</ul>

  <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
  <div class="container">
     <ul class="nav nav-tabs">
     <li><%= link_to "Home", root_path %></li>
     <li><%= link_to "About", about_path %></li>
  </ul>

  <% if flash[:notice] %>
         <div class="alert alert-success">
           <button type="button" class="close" data-dismiss="alert">&times;</button>
           <%= flash[:notice] %>
         </div>
       <% elsif flash[:alert] %>
         <div class="alert alert-warning">
           <button type="button" class="close" data-dismiss="alert">&times;</button>
           <%= flash[:alert] %>
         </div>
       <% end %>
<%= yield %>
<li><%= link_to "Wikis", wikis_path %></li>

</div>
</body>
</html>

app/views/users/show.html.erb
<h1>Hey <%=current_user.email %> thanks for becoming premium! Now you can see all the cool Wikis!!! :)</h1>

app/views/welcome/about.html.erb
<h1>Welcome#about</h1>
<p>Find me in app/views/welcome/about.html.erb</p>

  <script type="text/javascript">
       $(document).on("ready page:load", function () {
          blocmetrics.report("The About Page");
        })
  </script>

app/views/welcome/index.html.erb
<h1>Welcome!</h1>

  <script type="text/javascript">
       $(document).on("ready page:load", function () {
          blocmetrics.report("The About Page");
        })
  </script>

app/views/wikis/_form.html.erb
<% if current_user.admin? || current_user.premium? %>
  <div class="form-group">
    <%= f.label :private, class: 'checkbox' do %>
      <%= f.check_box :private %> Private wiki
    <% end %>
  </div>
<% end %>
<div class="form-group">
  <p>Collaborators</p>
  <% collaborator_user_ids = @wiki.collaborator_user_ids %>
  <% User.all.each do |user| %>
    <div class="user">
      <%= check_box_tag "wiki[collaborator_user_ids][]", user.id, collaborator_user_ids.include?(user.id) %>
      <%= user.name %>
    </div>
  <% end %>
</div>

app/views/wikis/edit.html.erb
<%= link_to "Add Collaborator", new_collaborator_path(@wiki), class: 'btn btn-primary' %>

app/views/wikis/index.html.erb
<h1>Hey there. This is the Wiki List</h1>
<%if current_user.admin? || current_user.premium?%>
<% @wikis.each do |wiki| %>
<p><%= link_to wiki.title, wiki %>
<% end %>
<% end %>
<%= link_to "New Wiki", new_wiki_path, class: 'btn btn-success' %>


  <script type="text/javascript">
       $(document).on("ready page:load", function () {
          blocmetrics.report("The About Page");
        })
  </script>

app/views/wikis/new.html.erb
<h1>New wiki</h1>
 <div class="row">
   <div class="col-md-4">
     <p>Guidelines for wikis</p>
     <ul>
       <li>Make sure it rhymes.</li>
       <li>Don't use the letter "A".</li>
       <li>The incessant use of hashtags will get you banned.</li>
     </ul>
   </div>
   <div class="col-md-8">
     <%= form_for @wiki do |f| %>
       <div class="form-group">
         <%= f.label :title %>
         <%= f.text_field :title, class: 'form-control', placeholder: "Enter wiki title" %>
       </div>
       <div class="form-group">
         <%= f.label :body %>
         <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter wiki body" %>
       </div>
       <div class="form-group">
         <%= f.submit "Save", class: 'btn btn-success' %>
       </div>
     <% end %>
   </div>
 </div>

app/views/wikis/show.html.erb
markdown.render("This is the wiki you chose. Happy reading!")
<h1><%= @wiki.title %></h1>
<p><%= @wiki.body %></p>
  <%= link_to "Edit", edit_wiki_path, class: 'btn btn-success' %>
<%= link_to "Delete", @wiki, method: :delete, class: 'btn btn-danger', data: {confirm: 'Are you sure you want to delete this?'} %>
<h2>Would you like to add a new collaboartor to this Wiki?</h1>